import Link from "next/link"
import { Award, BriefcaseBusiness, Building2, CheckCircle2, Compass, Link2, SearchX, Sparkles, Trophy } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { JobFilters } from "@/components/job-filters"
import { JobCard } from "@/components/job-card"
import { getJobs } from "@/app/actions/jobs"

const categories = ["All", "Technology", "Design", "Marketing", "Finance", "Healthcare", "Customer success", "Operations"]

export default async function JobsPage({ searchParams }: { searchParams: Promise<{ q?: string; location?: string; type?: string; category?: string }> }) {
  const sp = await searchParams
  const jobs = await getJobs({ q: sp.q, location: sp.location, type: sp.type, category: sp.category })
  return <div className="min-h-svh bg-background"><SiteHeader /><main className="mx-auto max-w-7xl px-4 py-6 lg:px-6"><div className="mb-5 flex items-center gap-2 text-sm text-muted-foreground"><Link href="/" className="hover:text-primary">Home</Link><span>/</span><span className="font-medium text-foreground">Explore jobs</span></div><div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)_240px] lg:items-start">
    <aside className="space-y-4"><SidePanel title="Categories" icon={<Compass className="h-4 w-4 text-primary" />}><div className="grid grid-cols-2 gap-2">{categories.map((category) => <Link key={category} href={category === "All" ? "/jobs" : `/jobs?category=${encodeURIComponent(category)}`} className={`rounded-lg border px-2 py-2 text-center text-xs font-semibold transition-colors ${sp.category === category || (!sp.category && category === "All") ? "border-primary bg-primary/10 text-primary" : "border-border bg-secondary/50 text-muted-foreground hover:border-primary/40 hover:text-primary"}`}>{category}</Link>)}</div></SidePanel><SidePanel title="Top picks" icon={<Trophy className="h-4 w-4 text-primary" />}><div className="space-y-3"><Rank name="Best match" value="Thoughtful teams" color="bg-accent" /><Rank name="New this week" value={`${jobs.length} open roles`} color="bg-primary/10" /></div></SidePanel><SidePanel title="For employers" icon={<Building2 className="h-4 w-4 text-primary" />}><p className="text-xs leading-relaxed text-muted-foreground">Reach motivated people who are ready for their next chapter.</p><Link href="/sign-up" className="mt-3 inline-flex text-xs font-bold text-primary hover:underline">Post a job →</Link></SidePanel></aside>
    <section className="min-w-0"><div className="mb-4"><h1 className="text-2xl font-bold tracking-tight">Explore opportunities</h1><p className="mt-1 text-sm text-muted-foreground">{jobs.length} role{jobs.length === 1 ? "" : "s"} available for your next move</p></div><JobFilters /><div className="mt-4 space-y-3">{jobs.length === 0 ? <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card py-20 text-center"><SearchX className="h-10 w-10 text-muted-foreground" /><p className="mt-3 font-semibold">No roles match your search</p><p className="mt-1 text-sm text-muted-foreground">Try adjusting your filters or search terms.</p></div> : jobs.map((job) => <JobCard key={job.id} job={job} />)}</div></section>
    <aside className="space-y-4"><SidePanel title="Why WorkHive" icon={<Sparkles className="h-4 w-4 text-primary" />}><p className="text-sm leading-relaxed text-muted-foreground">A calmer place to find work, meet teams, and make your next move with confidence.</p><div className="mt-4 space-y-2 border-t border-border pt-3"><Bullet text="Clear job details" /><Bullet text="Verified opportunities" /><Bullet text="Simple applications" /></div></SidePanel><SidePanel title="Quick links" icon={<Link2 className="h-4 w-4 text-primary" />}><div className="space-y-2 text-sm font-medium"><Link className="block text-muted-foreground hover:text-primary" href="/dashboard">My applications</Link><Link className="block text-muted-foreground hover:text-primary" href="/sign-up">Create a profile</Link><Link className="block text-muted-foreground hover:text-primary" href="/sign-up">Start hiring</Link></div></SidePanel><div className="px-1 text-xs leading-relaxed text-muted-foreground">WorkHive connects people with work that feels worth doing.</div></aside>
  </div></main></div>
}
function SidePanel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <div className="directory-shadow rounded-2xl border border-border bg-card p-4"><div className="mb-4 flex items-center gap-2 font-bold"><span>{icon}</span>{title}</div>{children}</div> }
function Bullet({ text }: { text: string }) { return <div className="flex items-center gap-2 border-b border-dashed border-border pb-2 text-xs text-muted-foreground last:border-0 last:pb-0"><CheckCircle2 className="h-3.5 w-3.5 text-chart-3" />{text}</div> }
function Rank({ name, value, color }: { name: string; value: string; color: string }) { return <div className="flex items-center gap-2"><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${color}`}><Award className="h-4 w-4 text-primary" /></span><div><p className="text-xs text-muted-foreground">{name}</p><p className="text-sm font-semibold">{value}</p></div></div> }
